package auction.infrastructure;

import auction.domain.AuctionSession;
import auction.domain.AuctionStatus;
import auction.domain.Lot;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Repository for AuctionSession entity - handles all database operations for AuctionSessions.
 * Uses DatabaseConnection for SQLite access.
 */
public class AuctionSessionRepository {
    private final DatabaseConnection dbConnection;
    private final LotRepository lotRepository;

    public AuctionSessionRepository() {
        this.dbConnection = DatabaseConnection.getInstance();
        this.lotRepository = new LotRepository();
    }

    /**
     * Save a new auction session to the database
     *
     * @return the auction session ID generated by the database
     */
    public int save(AuctionSession session, int lotId) {
        String sql = "INSERT INTO auction_sessions (title, lot_id, status) VALUES (?, ?, ?)";

        try (Connection conn = dbConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            pstmt.setString(1, session.getTitle());
            pstmt.setInt(2, lotId);
            pstmt.setString(3, session.getStatus() != null ? session.getStatus().name() : AuctionStatus.SCHEDULED.name());

            pstmt.executeUpdate();

            // Get the generated ID
            try (ResultSet rs = pstmt.getGeneratedKeys()) {
                if (rs.next()) {
                    int id = rs.getInt(1);
                    System.out.println("AuctionSession saved with ID: " + id);
                    return id;
                }
            }
        } catch (SQLException e) {
            System.err.println("Failed to save auction session");
            e.printStackTrace();
        }
        return -1;
    }

    /**
     * Get auction session by database ID
     */
    public AuctionSession findById(int id) {
        String sql = "SELECT * FROM auction_sessions WHERE id = ?";

        try (Connection conn = dbConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, id);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                return mapResultSetToAuctionSession(rs);
            }
        } catch (SQLException e) {
            System.err.println("Failed to find auction session with ID: " + id);
            e.printStackTrace();
        }
        return null;
    }

    /**
     * Get all auction sessions from database
     */
    public List<AuctionSession> findAll() {
        String sql = "SELECT * FROM auction_sessions ORDER BY id";
        List<AuctionSession> sessions = new ArrayList<>();

        try (Connection conn = dbConnection.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                sessions.add(mapResultSetToAuctionSession(rs));
            }
        } catch (SQLException e) {
            System.err.println("Failed to retrieve auction sessions");
            e.printStackTrace();
        }
        return sessions;
    }

    /**
     * Get auction sessions by status (e.g., SCHEDULED, STARTED)
     */
    public List<AuctionSession> findByStatus(AuctionStatus... statuses) {
        if (statuses.length == 0) {
            return new ArrayList<>();
        }

        // Build SQL with IN clause
        StringBuilder sql = new StringBuilder("SELECT * FROM auction_sessions WHERE status IN (");
        for (int i = 0; i < statuses.length; i++) {
            sql.append("?");
            if (i < statuses.length - 1) {
                sql.append(", ");
            }
        }
        sql.append(") ORDER BY id");

        List<AuctionSession> sessions = new ArrayList<>();

        try (Connection conn = dbConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql.toString())) {

            // Set parameters
            for (int i = 0; i < statuses.length; i++) {
                pstmt.setString(i + 1, statuses[i].name());
            }

            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                sessions.add(mapResultSetToAuctionSession(rs));
            }
        } catch (SQLException e) {
            System.err.println("Failed to retrieve auction sessions by status");
            e.printStackTrace();
        }
        return sessions;
    }

    /**
     * Update an existing auction session
     */
    public boolean update(int id, AuctionSession session) {
        String sql = "UPDATE auction_sessions SET title = ?, status = ? WHERE id = ?";

        try (Connection conn = dbConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, session.getTitle());
            pstmt.setString(2, session.getStatus() != null ? session.getStatus().name() : AuctionStatus.SCHEDULED.name());
            pstmt.setInt(3, id);

            int rowsAffected = pstmt.executeUpdate();
            return rowsAffected > 0;
        } catch (SQLException e) {
            System.err.println("Failed to update auction session with ID: " + id);
            e.printStackTrace();
        }
        return false;
    }

    /**
     * Delete an auction session by ID
     */
    public boolean delete(int id) {
        String sql = "DELETE FROM auction_sessions WHERE id = ?";

        try (Connection conn = dbConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, id);
            int rowsAffected = pstmt.executeUpdate();
            return rowsAffected > 0;
        } catch (SQLException e) {
            System.err.println("Failed to delete auction session with ID: " + id);
            e.printStackTrace();
        }
        return false;
    }

    /**
     * Helper method to map ResultSet to AuctionSession object
     */
    private AuctionSession mapResultSetToAuctionSession(ResultSet rs) throws SQLException {
        AuctionSession session = new AuctionSession();

        // Set title
        String title = rs.getString("title");
        session.setTitle(title);

        // Set status
        String statusStr = rs.getString("status");
        if (statusStr != null) {
            session.setStatus(AuctionStatus.valueOf(statusStr));
        }

        // Load the associated lot
        int lotId = rs.getInt("lot_id");
        Lot lot = lotRepository.findById(lotId);
        if (lot != null) {
            List<Lot> catalog = new ArrayList<>();
            catalog.add(lot);
            session.setCatalog(catalog);
        }

        return session;
    }

    /**
     * Get total count of auction sessions
     */
    public int count() {
        String sql = "SELECT COUNT(*) FROM auction_sessions";

        try (Connection conn = dbConnection.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            if (rs.next()) {
                return rs.getInt(1);
            }
        } catch (SQLException e) {
            System.err.println("Failed to count auction sessions");
            e.printStackTrace();
        }
        return 0;
    }
}
