package auction.infrastructure;

import auction.domain.Lot;
import auction.domain.LotStatus;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Repository for Lot entity - handles all database operations for Lots.
 * Uses DatabaseConnection for SQLite access.
 */
public class LotRepository {
    private final DatabaseConnection dbConnection;

    public LotRepository() {
        this.dbConnection = DatabaseConnection.getInstance();
    }

    /**
     * Save a new lot to the database
     *
     * @return the lot ID generated by the database
     */
    public int save(Lot lot) {
        String sql = "INSERT INTO lots (name, estimate_price, reserve_price, status, no_reserve) VALUES (?, ?, ?, ?, ?)";

        try (Connection conn = dbConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            pstmt.setString(1, lot.getName());
            pstmt.setObject(2, lot.getEstimatePrice());
            pstmt.setObject(3, lot.getReservePrice());
            pstmt.setString(4, lot.getStatus() != null ? lot.getStatus().name() : LotStatus.UNSOLD.name());
            pstmt.setInt(5, lot.getNoReserve() != null && lot.getNoReserve() ? 1 : 0);

            pstmt.executeUpdate();

            // Get the generated ID
            try (ResultSet rs = pstmt.getGeneratedKeys()) {
                if (rs.next()) {
                    int id = rs.getInt(1);
                    System.out.println("Lot saved with ID: " + id);
                    return id;
                }
            }
        } catch (SQLException e) {
            System.err.println("Failed to save lot: " + lot.getName());
            e.printStackTrace();
        }
        return -1;
    }

    /**
     * Get lot by database ID
     */
    public Lot findById(int id) {
        String sql = "SELECT * FROM lots WHERE id = ?";

        try (Connection conn = dbConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, id);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                return mapResultSetToLot(rs);
            }
        } catch (SQLException e) {
            System.err.println("Failed to find lot with ID: " + id);
            e.printStackTrace();
        }
        return null;
    }

    /**
     * Get all lots from database
     */
    public List<Lot> findAll() {
        String sql = "SELECT * FROM lots ORDER BY id";
        List<Lot> lots = new ArrayList<>();

        try (Connection conn = dbConnection.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                lots.add(mapResultSetToLot(rs));
            }
        } catch (SQLException e) {
            System.err.println("Failed to retrieve lots");
            e.printStackTrace();
        }
        return lots;
    }

    /**
     * Update an existing lot
     */
    public boolean update(int id, Lot lot) {
        String sql = "UPDATE lots SET name = ?, estimate_price = ?, reserve_price = ?, status = ?, no_reserve = ? WHERE id = ?";

        try (Connection conn = dbConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, lot.getName());
            pstmt.setObject(2, lot.getEstimatePrice());
            pstmt.setObject(3, lot.getReservePrice());
            pstmt.setString(4, lot.getStatus() != null ? lot.getStatus().name() : LotStatus.UNSOLD.name());
            pstmt.setInt(5, lot.getNoReserve() != null && lot.getNoReserve() ? 1 : 0);
            pstmt.setInt(6, id);

            int rowsAffected = pstmt.executeUpdate();
            return rowsAffected > 0;
        } catch (SQLException e) {
            System.err.println("Failed to update lot with ID: " + id);
            e.printStackTrace();
        }
        return false;
    }

    /**
     * Delete a lot by ID
     */
    public boolean delete(int id) {
        String sql = "DELETE FROM lots WHERE id = ?";

        try (Connection conn = dbConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, id);
            int rowsAffected = pstmt.executeUpdate();
            return rowsAffected > 0;
        } catch (SQLException e) {
            System.err.println("Failed to delete lot with ID: " + id);
            e.printStackTrace();
        }
        return false;
    }

    /**
     * Helper method to map ResultSet to Lot object
     */
    private Lot mapResultSetToLot(ResultSet rs) throws SQLException {
        String name = rs.getString("name");

        // SQLite stores REAL as Double, we need to convert to Float
        Double estimatePriceDouble = (Double) rs.getObject("estimate_price");
        Float estimatePrice = estimatePriceDouble != null ? estimatePriceDouble.floatValue() : null;

        Double reservePriceDouble = (Double) rs.getObject("reserve_price");
        Float reservePrice = reservePriceDouble != null ? reservePriceDouble.floatValue() : null;

        Lot lot = new Lot.LotBuilder(name)
                .estimatePrice(estimatePrice)
                .reservePrice(reservePrice)
                .build();

        // Set status
        String statusStr = rs.getString("status");
        if (statusStr != null) {
            lot.setStatus(LotStatus.valueOf(statusStr));
        }

        // Set noReserve
        int noReserve = rs.getInt("no_reserve");
        lot.setNoReserve(noReserve == 1);

        return lot;
    }

    /**
     * Get total count of lots
     */
    public int count() {
        String sql = "SELECT COUNT(*) FROM lots";

        try (Connection conn = dbConnection.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            if (rs.next()) {
                return rs.getInt(1);
            }
        } catch (SQLException e) {
            System.err.println("Failed to count lots");
            e.printStackTrace();
        }
        return 0;
    }
}
